import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const faqItems = [
  {
    question: 'What databases are supported by Query GPT?',
    answer: 'Currently, Query GPT supports generating queries for SQL, PostgreSQL, MySQL, MongoDB, and other popular database systems. Our querygpt service is continuously adding support for more database types.'
  },
  {
    question: 'How accurate are the queries generated by querygpt?',
    answer: 'The accuracy of queries from Query GPT depends on the clarity of your question and the database schema provided. In most cases, you\'ll get highly accurate queries that require minimal or no adjustments.'
  },
  {
    question: 'Do I need to provide my database schema to Query GPT?',
    answer: 'Providing your schema to querygpt is optional but recommended for more accurate results. Without a schema, Query GPT will make its best guess based on your question.'
  },
  {
    question: 'Is my data safe with Query GPT?',
    answer: 'Yes, querygpt doesn\'t store your database schema or queries. All processing happens in your browser session and is not persisted on our servers.'
  },
  {
    question: 'Can I use Query GPT for complex queries?',
    answer: 'Absolutely! Query GPT is designed to handle complex queries involving multiple tables, joins, aggregations, and more. For very complex queries, you might need to provide more context about your database structure to querygpt.'
  },
  {
    question: 'Is there a limit to the number of queries I can generate with querygpt?',
    answer: 'Our free tier of Query GPT allows for a generous number of queries per day. For unlimited usage and additional features, consider upgrading to our premium querygpt plan.'
  }
];

const FAQ = () => {
  return (
    <section className="py-16 px-4 md:px-8 bg-secondary/50">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-12 text-center">Frequently Asked Questions About Query GPT</h2>
        <Accordion type="single" collapsible className="w-full">
          {faqItems.map((item, index) => (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger className="text-lg font-semibold">{item.question}</AccordionTrigger>
              <AccordionContent className="text-muted-foreground">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default FAQ; 